- name: test my new module
  hosts: localhost
  tasks:
  - name: run the new module
    postgresql_user:
      user: test
      password: "reset"
      db: ansible
      login_host: host.docker.internal
      login_password: secret
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
